//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-memory-linter (cli)
//! AC description: Exit code reflects findings: 0 = no findings, 1 = at least one finding, 2 = invocation error (bad path, unreadable file, malformed args). Exit codes are stable across runs on identical inputs.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac7() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC7 not yet implemented — see file header");
}
