//! Acceptance test for AC8 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: recall-fastembed-embedder (cli)
//! AC description: First fastembed query in a fresh process with the model already cached completes within 2s wall time on this laptop (cold cache; second query <100ms).
//! Test predicate: tests/acceptance_ac8.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac8() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC8 not yet implemented — see file header");
}
