//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-memory-linter (cli)
//! AC description: Walks the root recursively, treats every *.md file as a memory entry, and ignores non-Markdown files and dot-prefixed directories.
//! Test predicate: tests/acceptance_ac2.rs
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac2() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC2 not yet implemented — see file header");
}
