//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-memory-linter (cli)
//! AC description: Detects duplicates: two entries with byte-identical body (post-frontmatter, trimmed) produce one finding kind=`duplicate` listing all paths in deterministic sorted order.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac4() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC4 not yet implemented — see file header");
}
