//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-fastembed-embedder (cli)
//! AC description: Cargo.toml depends on `fastembed` (any 4.x or 5.x), pinned with a tilde or caret range, and the workspace builds clean.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac1() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC1 not yet implemented — see file header");
}
