//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-fastembed-embedder (cli)
//! AC description: Semantic discrimination: given two memories — one about "package manager preferences" and one about "unrelated text" — a hybrid query for the synonym phrase "dependency tool" ranks the package-manager memory above the unrelated one with FastembedEmbedder. The same query with HashEmbedder produces the inverse or null ranking (test asserts the difference).
//! Test predicate: tests/acceptance_ac5.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac5` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use recall::embeddings::{Embedder, FastembedEmbedder, HashEmbedder, cosine};

#[test]
fn acceptance_ac5() {
    // AC5: Semantic discrimination. A query for the synonym phrase
    // "dependency tool" should rank a package-manager memory above an
    // unrelated memory under FastembedEmbedder, with a meaningful
    // margin that HashEmbedder cannot achieve.
    let pkg_mgr = "user prefers pnpm as the package manager for TypeScript projects";
    let unrelated = "the kettle whistled while the cat slept on the windowsill";
    let query = "dependency tool";

    let fe = FastembedEmbedder::new().expect("init fastembed");
    let fe_q = fe.embed(query).unwrap();
    let fe_pkg = fe.embed(pkg_mgr).unwrap();
    let fe_un = fe.embed(unrelated).unwrap();
    let fe_sim_pkg = cosine(&fe_q, &fe_pkg);
    let fe_sim_un = cosine(&fe_q, &fe_un);

    let he = HashEmbedder::new();
    let he_q = he.embed(query).unwrap();
    let he_pkg = he.embed(pkg_mgr).unwrap();
    let he_un = he.embed(unrelated).unwrap();
    let he_sim_pkg = cosine(&he_q, &he_pkg);
    let he_sim_un = cosine(&he_q, &he_un);

    // Fastembed must rank the package-manager memory above the unrelated one.
    assert!(
        fe_sim_pkg > fe_sim_un,
        "fastembed expected pkg>un but pkg={fe_sim_pkg} un={fe_sim_un}"
    );

    // The gap under fastembed must materially exceed the gap under hash —
    // this is the falsifiable "synonyms now work" assertion.
    let fe_gap = fe_sim_pkg - fe_sim_un;
    let he_gap = he_sim_pkg - he_sim_un;
    assert!(
        fe_gap > he_gap + 0.05,
        "fastembed gap {fe_gap} should beat hash gap {he_gap} by >0.05"
    );
}
