//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-memory-linter (cli)
//! AC description: Parses YAML frontmatter (optional, fenced by ---). Recognizes `last_recalled_at` and `created_at` as RFC3339 timestamps; flags entries whose newest of (last_recalled_at, created_at, file mtime) is older than --stale-days (default 30) as finding kind=`stale`.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac3() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC3 not yet implemented — see file header");
}
