//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-fastembed-embedder (cli)
//! AC description: Cargo.toml depends on `fastembed` (any 4.x or 5.x), pinned with a tilde or caret range, and the workspace builds clean.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac1() {
    // AC1: Cargo.toml depends on `fastembed`, pinned with a tilde or
    // caret range. Just-built crate must compile (we're here, so it does).
    let toml = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/Cargo.toml"))
        .expect("read Cargo.toml");
    let dep_line = toml
        .lines()
        .find(|l| l.trim_start().starts_with("fastembed"))
        .expect("Cargo.toml must contain a fastembed dependency line");
    // Accept caret (default) or tilde version constraints, with or
    // without a `version =` key.
    let constraint_ok = dep_line.contains('"')
        && (dep_line.contains("\"~") || dep_line.contains("\"^") || dep_line.contains("\"4") || dep_line.contains("\"5"));
    assert!(
        constraint_ok,
        "fastembed dep line should pin a 4.x or 5.x version: {dep_line}"
    );
}
