//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-fastembed-embedder (cli)
//! AC description: FastembedEmbedder reports `embedding_id = "fastembed:bge-small-en-v1.5"` and `embedding_dim = 384` (BGE-small's actual dimensionality). HashEmbedder continues to report its own id and 256-dim.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use recall::embeddings::{Embedder, FastembedEmbedder, HashEmbedder};

#[test]
fn acceptance_ac3() {
    // AC3: FastembedEmbedder reports
    //   embedding_id = "fastembed:bge-small-en-v1.5"
    //   embedding_dim = 384
    // HashEmbedder keeps its own id and 256-dim.
    let fe = FastembedEmbedder::new().expect("init fastembed");
    assert_eq!(fe.id(), "fastembed:bge-small-en-v1.5");
    assert_eq!(fe.dim(), 384);

    let he = HashEmbedder::new();
    assert_eq!(he.dim(), 256);
    assert!(he.id().starts_with("hash-v1"), "hash id was {}", he.id());
    assert_ne!(fe.id(), he.id());

    // Embed-output dimensionality matches reported dim.
    let v = fe.embed("dimensionality check").expect("embed");
    assert_eq!(v.len(), 384);
    let hv = he.embed("dimensionality check").expect("embed");
    assert_eq!(hv.len(), 256);
}
