//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-memory-linter (cli)
//! AC description: CLI binary `recall-lint` accepts a positional path to a memory root directory and exits 0 when the directory is empty, emitting an empty findings array in JSON mode.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac1() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC1 not yet implemented — see file header");
}
