//! Acceptance test for AC10 (MAY) — generated by `autobuilder scaffold`.
//!
//! Project: recall-memory-linter (cli)
//! AC description: Supports `--ignore <glob>` (repeatable) to skip paths matching the glob; ignored files contribute neither to duplicate detection nor to wiki-link resolution.
//! Test predicate: tests/acceptance_ac10.rs
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac10() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC10 not yet implemented — see file header");
}
