//! Acceptance test for AC8 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: recall-memory-linter (cli)
//! AC description: Lints a fixture corpus of 100 *.md files in under 500ms wall time on a warm cache (single-thread). Verified by a `#[ignore]`-gated bench-style test that asserts elapsed < 500ms.
//! Test predicate: tests/acceptance_ac8.rs
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac8() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC8 not yet implemented — see file header");
}
