//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-fastembed-embedder (cli)
//! AC description: CLI accepts `--embedder hash|fastembed`. When the flag is absent, the default is `fastembed`. `hash` remains selectable for offline/test contexts.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use recall::embeddings::EmbedderKind;

#[test]
fn acceptance_ac4() {
    // AC4: CLI accepts `--embedder hash|fastembed`. Default = fastembed.

    // Library-side parser matches the CLI's accepted values.
    assert_eq!(EmbedderKind::parse("hash").unwrap(), EmbedderKind::Hash);
    assert_eq!(EmbedderKind::parse("fastembed").unwrap(), EmbedderKind::Fastembed);
    assert!(EmbedderKind::parse("ollama").is_err(), "invalid value should error");

    // The recall binary's --help text must surface the flag and its default.
    let out = std::process::Command::new(env!("CARGO_BIN_EXE_recall"))
        .arg("--help")
        .output()
        .expect("spawn recall --help");
    assert!(out.status.success(), "recall --help exited non-zero");
    let help = String::from_utf8_lossy(&out.stdout);
    assert!(help.contains("--embedder"), "--embedder flag missing from --help:\n{help}");
    assert!(help.contains("fastembed"), "fastembed default missing from --help:\n{help}");
    assert!(help.contains("hash"), "hash option missing from --help:\n{help}");
}
