//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-memory-linter (cli)
//! AC description: Output mode is selectable: `--format text` (default, human-readable, grouped by kind) or `--format json` (stable schema with top-level `findings` array; each finding has `kind`, `paths`, and kind-specific fields). JSON output is deterministic given fixed input.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac6() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC6 not yet implemented — see file header");
}
