//! Acceptance test for AC5 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: recall-memory-linter (cli)
//! AC description: Detects broken `[[wiki-links]]`: a link `[[target]]` resolves if any *.md file under the root has stem `target` or relative path `target.md`; otherwise emits finding kind=`broken_link` with source path, target, and 1-indexed line number.
//! Test predicate: tests/acceptance_ac5.rs
//!
//! READ-ONLY after scaffold. To change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold.

#[test]
fn acceptance_ac5() {
    // TODO(edit-agent): implement the test body that verifies the
    // AC description above. Until implemented, this test fails so the
    // iterate-and-prove loop sees a real signal.
    panic!("AC AC5 not yet implemented — see file header");
}
